export const architectureCards = [
  { title: 'Enterprise Monolith Modernization', tags: ['Legacy Modernization', 'DDD', 'Event Sourcing', 'Java', 'Oracle'], description: 'Modernizing a large enterprise platform by gradually decoupling business capabilities, migrating database-centric business logic into Java services and evolving CRUD-oriented domains towards DDD and Event Sourcing.' },
  { title: 'Configurable Market Data Processing', tags: ['FIX', 'Microservices', 'Configuration-Driven Architecture'], description: 'A configurable market-data processing and reporting service supporting multiple delivery mechanisms.' },
  { title: 'Domain-Driven Telecommunications Platform', tags: ['DDD', 'CQRS', 'Event Sourcing', 'Go'], description: 'Evolving an enterprise telecommunications application towards domain-driven and event-oriented architecture.' },
];

export const caseStudy = {
  title: 'CDC → Event Integration Platform',
  tags: ['CDC', 'Kafka', 'Event-Driven Architecture', 'Deduplication', 'Configuration-Driven Architecture'],
  problem: [
    'The platform integrated with a third-party analytics system by forwarding data derived from CDC messages generated by the core platform.',
    'The CDC stream contained changes across multiple business areas, including balances, bonuses, bets and settlements, payments, users and custom events.',
    'However, the available CDC payload did not provide sufficient previous-state information for reliable business-level event detection.',
    'As a result, many technically valid database changes had no meaningful value for the downstream analytics system. Redundant events could also lead to data collisions and inconsistencies between the platform and third-party dashboards.',
    'The existing implementation additionally generated significant and unnecessary load on the Oracle database due to inefficient database access patterns.',
  ],
  solution: 'Designed and developed a new event-driven integration service acting as a CDC processor and event transformer between the core platform and external integrations. Instead of forwarding raw CDC changes, the service transforms low-level database changes into meaningful, integration-specific events. The architecture was intentionally designed as a reusable integration platform rather than a solution tailored to a single third party.',
  outcomes: ['Reduced redundant event traffic', 'Improved consistency of downstream analytics data', 'Reduced unnecessary database access', 'Separated CDC infrastructure from integration-specific behavior', 'Reusable infrastructure for future third-party integrations', 'Runtime configuration changes without service restarts', 'Scalable foundation for event-driven integrations'],
};
